/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicZenopayWebhookRouteImport } from './routes/api/public/zenopay-webhook'
import { Route as ApiPublicFlutterwaveWebhookRouteImport } from './routes/api/public/flutterwave-webhook'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicZenopayWebhookRoute = ApiPublicZenopayWebhookRouteImport.update({
  id: '/api/public/zenopay-webhook',
  path: '/api/public/zenopay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFlutterwaveWebhookRoute =
  ApiPublicFlutterwaveWebhookRouteImport.update({
    id: '/api/public/flutterwave-webhook',
    path: '/api/public/flutterwave-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/api/public/zenopay-webhook': typeof ApiPublicZenopayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/api/public/zenopay-webhook': typeof ApiPublicZenopayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/api/public/zenopay-webhook': typeof ApiPublicZenopayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/pricing'
    | '/settings'
    | '/api/public/flutterwave-webhook'
    | '/api/public/zenopay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/pricing'
    | '/settings'
    | '/api/public/flutterwave-webhook'
    | '/api/public/zenopay-webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/pricing'
    | '/settings'
    | '/api/public/flutterwave-webhook'
    | '/api/public/zenopay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  ApiPublicFlutterwaveWebhookRoute: typeof ApiPublicFlutterwaveWebhookRoute
  ApiPublicZenopayWebhookRoute: typeof ApiPublicZenopayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/zenopay-webhook': {
      id: '/api/public/zenopay-webhook'
      path: '/api/public/zenopay-webhook'
      fullPath: '/api/public/zenopay-webhook'
      preLoaderRoute: typeof ApiPublicZenopayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/flutterwave-webhook': {
      id: '/api/public/flutterwave-webhook'
      path: '/api/public/flutterwave-webhook'
      fullPath: '/api/public/flutterwave-webhook'
      preLoaderRoute: typeof ApiPublicFlutterwaveWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  ApiPublicFlutterwaveWebhookRoute: ApiPublicFlutterwaveWebhookRoute,
  ApiPublicZenopayWebhookRoute: ApiPublicZenopayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
